version: "3.9"
services:
#    server:
#        container_name: server_api
#        build: .
#        ports:
#            - "8080:8080"
#        expose:
#            - 8080
#        networks:
#            - server-network
#        depends_on:
#            - database
    database:
        restart: always
        container_name: database
        image: postgres:latest
        volumes:
            - ./docker-data:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: someshop
            POSTGRES_ROOT_PASSWORD: "root"
            PGDATA : /var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - 5432
        networks:
            - server-network
networks:
    server-network:
        driver: bridge